[build-system]
requires = ["setuptools>=74.1", "wheel", "numpy", "matplotlib", "scipy", "scikit-learn"]
build-backend = "setuptools.build_meta"

[project]
name = "core_toolbox_python"
version = "0.1.0"
description = "A toolbox of camera, Plücker, and transformation utilities"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
  "numpy",
  "matplotlib",
  "scipy",
  "scikit-learn",
]
authors = [
  { name="Rhys Evans & Seppe Sels" },
]
license = { text = "MIT" }
