name: Build & Publish Wheels

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request: { }
  push:
    tags:
      - 'v*'

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tool
        run: python -m pip install --upgrade build

      - name: Build wheel
        run: python -m build --wheel --outdir dist

      - name: Upload wheel artifact (${ { matrix.python-version } })
        uses: actions/upload-artifact@v4
        with:
          name: core-toolbox-wheel-${{ matrix.python-version }}
          path: dist/*.whl


  publish:
    needs: build-wheels
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - uses: softprops/action-gh-release@v1
        with:
          files: '**/*.whl'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}