name: Build & Publish Wheels

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request: { }
  push:
    tags:
      - 'v*'

jobs:
  build-wheels:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-14]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/*.whl


  publish:
    needs: build-wheels
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub release and upload wheels
        uses: softprops/action-gh-release@v1
        with:
          files: '**/*.whl'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
