name: Build & Publish Wheels

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request: { }
  push:
    tags:
      - 'v*'

jobs:
  build-wheels:
    name: Build & Package Wheels
    os: [ubuntu-latest, windows-latest, macos-15]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU for multi-arch
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Prepare cibuildwheel environment
        run: |
          ver="${{ matrix.python-version }}"
          ver_nodot="${ver//./}"
          echo "CIBW_BUILD=cp${ver_nodot}-*" >> $GITHUB_ENV
          echo "CIBW_ARCHS=x86_64 aarch64"    >> $GITHUB_ENV
          echo "CIBW_ENVIRONMENT_MACOS=MACOSX_DEPLOYMENT_TARGET=15.0" >> $GITHUB_ENV
      - name: Install cibuildwheel
        run: python -m pip install --upgrade cibuildwheel==2.23.3

      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.23.3
        with:
          output-dir: wheelhouse

      - name: Repair Linux Wheels
        if: runner.os == 'Linux'
        run: |
          pip install auditwheel
          mkdir -p repaired
          for whl in wheelhouse/*.whl; do
            if [[ "$whl" == *x86_64*.whl ]]; then
              auditwheel repair "$whl" -w repaired/
            else
              cp "$whl" repaired/
            fi
          done
      - name: Delocate macOS Wheels
        if: runner.os == 'macOS'
        run: |
          pip install delocate-wheel
          mkdir -p repaired
          delocate-wheel -w repaired wheelhouse/*.whl
      - name: Upload Wheels Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.python-version }}
          path: repaired/*.whl

  publish:
    needs: build-wheels
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - uses: softprops/action-gh-release@v1
        with:
          files: '**/*.whl'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}