name: Build & Publish Wheels

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request: { }
  push:
    tags:
      - 'v*'

jobs:
  build-wheels:
    name: Build & Package Wheels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-15 ]
        python-version: [ '3.10', '3.11', '3.12' ]

    steps:
      - uses: actions/checkout@v4

      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.23.3
        with:
          output-dir: wheelhouse

  publish:
    needs: build-wheels
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - uses: softprops/action-gh-release@v1
        with:
          files: '**/*.whl'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}